[package]
name = "chromadisc"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
derive_more = { version = "2.1.1", features = ["full"] }
libcdio-sys = "1.0.0"
thiserror = "2.0.17"
