[package]
name = "mmc-errors"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0.104"
quote = "1.0.42"
syn = { version = "2.0.112", features = ["full"] }

[lib]
proc-macro = true
